Feature: Realizar uma consulta no dasboard Produto utilizando todos os filtro​​s

    
     Scenario Outline: Realizar uma consulta no dasboard Produto utilizando todos os filtro​​s.Cena:<n>
	Given Estou no dashboard "Produto" do setor "Shop"
     When Habilito o filtro de "<filtro>"
     And Seleciono a base "<base>"
     And Seleciono o produto "<produto>"
     And Seleciono o caminho "<caminho>"
     And Seleciono a funcionalidade "<funcionalidade>"
     And Seleciono a característica "<caracteristica>"
     And Seleciono a versão "<versao>"
     And Seleciono o cliente "<cliente>"
     And Seleciono a categoria "<categoria>"
     And Seleciono o CNAE Cliente "<CNAE Cliente>"
     And Seleciono o CNAE Funcionalidade "<CNAE Funcionalidade>"
     And Seleciono o sem uso como "<semuso>"
     And Seleciono as novas funcionalidades como "<novasfun>"
     And Seleciono incluir cliente interno como "<interno>"
     And Seleciono o peso abaixo de "<pesoabaixo>"
     And Seleciono o peso acima de "<pesoacima>"
     And Seleciono a data inicial "01/01/2019"
     And Seleciono a data final "31/01/2019"
     And Clico em consultar
     Then O sistema demonstrará as informações de acordo com os filtros utilizados
     Examples:
     |n |filtro                                                                                                                                                                                        |base  |produto  |caminho                                             |funcionalidade          |caracteristica|versao |cliente|categoria   |CNAE Cliente|CNAE Funcionalidade       |semuso|novasfun|interno |pesoabaixo|pesoacima|
     |1 |caminho, funcionalidade, característica, versão, cliente, categoria, CNAE Cliente, CNAE Funcionalidade, sem uso, novas funcionalidades, incluir cliente interno, Peso abaixo de, Peso acima de|900104|Wshop    |Principal>Vendas>Vender>Nota Facil                  |EMISSAO OTIMIZADA DE NFE|POSTGRE       |6.1334 |055691 |movimentação|4744-0/99   |vazio                     |não   |não     |não     |3         |1        |
     |2 |caminho                                                                                                                                                                                       |vazio |vazio    |Principal>Vendas>Vender>Nota Facil                  |vazio                   |vazio         |vazio  |vazio  |vazio       |vazio       |vazio                     |vazio |vazio   |vazio   |vazio     |vazio    |
     |3 |funcionalidade                                                                                                                                                                                |vazio |vazio    |vazio                                               |EMISSAO OTIMIZADA DE NFE|vazio         |vazio  |vazio  |vazio       |vazio       |vazio                     |vazio |vazio   |vazio   |vazio     |vazio    |
     |4 |característica                                                                                                                                                                                |vazio |vazio    |vazio                                               |vazio                   |POSTGRE       |vazio  |vazio  |vazio       |vazio       |vazio                     |vazio |vazio   |vazio   |vazio     |vazio    |
     |5 |versão                                                                                                                                                                                        |vazio |vazio    |vazio                                               |vazio                   |vazio         |6.1334 |vazio  |vazio       |vazio       |vazio                     |vazio |vazio   |vazio   |vazio     |vazio    |
     |6 |cliente                                                                                                                                                                                       |vazio |vazio    |vazio                                               |vazio                   |vazio         |vazio  |055691 |vazio       |vazio       |vazio                     |vazio |vazio   |vazio   |vazio     |vazio    |
     |7 |categoria                                                                                                                                                                                     |vazio |vazio    |vazio                                               |vazio                   |vazio         |vazio  |vazio  |movimentação|vazio       |vazio                     |vazio |vazio   |vazio   |vazio     |vazio    |
     |8 |CNAE Cliente                                                                                                                                                                                  |vazio |vazio    |vazio                                               |vazio                   |vazio         |vazio  |vazio  |vazio       |4744-0/99   |vazio                     |vazio |vazio   |vazio   |vazio     |vazio    |
     |11|novas funcionalidades                                                                                                                                                                         |vazio |vazio    |vazio                                               |vazio                   |vazio         |vazio  |vazio  |vazio       |vazio       |vazio                     |vazio |sim     |vazio   |vazio     |vazio    |
     |12|incluir cliente interno                                                                                                                                                                       |vazio |vazio    |vazio                                               |vazio                   |vazio         |vazio  |vazio  |vazio       |vazio       |vazio                     |vazio |vazio   |sim     |vazio     |vazio    |
     |13|peso abaixo de                                                                                                                                                                                |vazio |vazio    |vazio                                               |vazio                   |vazio         |vazio  |vazio  |vazio       |vazio       |vazio                     |vazio |vazio   |vazio   |8         |vazio    |
     |14|peso acima de                                                                                                                                                                                 |vazio |vazio    |vazio                                               |vazio                   |vazio         |vazio  |vazio  |vazio       |vazio       |vazio                     |vazio |vazio   |vazio   |vazio     |1        |
     |15|funcionalidade                                                                                                                                                                                |vazio |Wshop    |vazio                                               |EMISSAO OTIMIZADA DE NFE|vazio         |vazio  |vazio  |vazio       |vazio       |vazio                     |vazio |vazio   |vazio   |vazio     |vazio    |
     |16|funcionalidade, caminho                                                                                                                                                                       |vazio |Wshop    |Principal>Vendas>Vender>Nota Facil                  |EMISSAO OTIMIZADA DE NFE|vazio         |vazio  |vazio  |vazio       |vazio       |vazio                     |vazio |vazio   |vazio   |vazio     |vazio    |
     |17|caminho, característica                                                                                                                                                                       |vazio |Wshop    |Principal>Vendas>Vender>Nota Facil                  |vazio                   |POSTGRE       |vazio  |vazio  |vazio       |vazio       |vazio                     |vazio |vazio   |vazio   |vazio     |vazio    |
     |18|versão                                                                                                                                                                                        |vazio |Wshop    |vazio                                               |vazio                   |vazio         |6.1334 |vazio  |vazio       |vazio       |vazio                     |vazio |vazio   |vazio   |vazio     |vazio    |
     |19|caminho, característica, CNAE Cliente                                                                                                                                                         |vazio |vazio    |Principal>Vendas>Vender>Nota Facil                  |EMISSAO OTIMIZADA DE NFE|vazio         |vazio  |vazio  |vazio       |4744-0/99   |vazio                     |vazio |vazio   |vazio   |vazio     |vazio    |
     |20|novas funcionalidades, peso abaixo de                                                                                                                                                         |vazio |Wshop    |vazio                                               |vazio                   |vazio         |vazio  |vazio  |vazio       |vazio       |vazio                     |vazio |sim     |vazio   |8         |vazio    |
     |21|caminho, cliente, categoria, sem uso                                                                                                                                                          |vazio |vazio    |Principal>Vendas>Vender>Nota Facil                  |vazio                   |vazio         |vazio  |055691 |movimentação|vazio       |vazio                     |não   |vazio   |vazio   |vazio     |vazio    |
     |22|categoria, CNAE Funcionalidade                                                                                                                                                                |900104|Wshop    |vazio                                               |vazio                   |vazio         |vazio  |vazio  |movimentação|4744-0/99   |vazio                     |vazio |vazio   |vazio   |vazio     |vazio    |
     |23|funcionalidade, cliente, incluir cliente interno                                                                                                                                              |vazio |Wshop    |Principal>Vendas>Vender>Nota Facil                  |vazio                   |vazio         |vazio  |vazio  |movimentação|vazio       |vazio                     |vazio |vazio   |vazio   |vazio     |vazio    | 